import axios from 'axios';
import { exec } from 'child_process';
import { app, BrowserWindow, ipcMain } from 'electron';
import WebSocket from 'ws';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

let ws: WebSocket | null = null;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) app.quit();

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
};

app.commandLine.appendSwitch('ignore-certificate-errors');

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit();
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) createWindow();
});

// Handle HTTP requests
ipcMain.handle('http-request', async (_event, { url, method, headers, body }) => {
  try {
    const response = await axios({
      url,
      method,
      headers,
      data: body,
      maxBodyLength: Infinity,
      maxContentLength: Infinity,
      responseType: 'arraybuffer',
      validateStatus: () => true,
    });

    const contentType =
      (response.headers && (response.headers['content-type'] || response.headers['Content-Type'])) || '';
    const data = response.data;
    let responseBody: string;

    try {
      if (
        data instanceof ArrayBuffer ||
        (data && typeof data === 'object' && typeof (data as any).byteLength === 'number')
      ) {
        const uint8 = new Uint8Array(data as any);
        responseBody = new TextDecoder().decode(uint8);

        if (contentType.includes('application/json')) {
          try {
            responseBody = JSON.stringify(JSON.parse(responseBody), null, 2);
          } catch {
            // Keep as plain text if JSON parsing fails
          }
        }
      } else if (typeof data === 'string') {
        responseBody = data;
      } else {
        responseBody = typeof data === 'object' ? JSON.stringify(data, null, 2) : String(data);
      }
    } catch {
      try {
        responseBody = String(data);
      } catch {
        responseBody = '[unprintable response]';
      }
    }

    return {
      status: `${response.status} ${response.statusText}`,
      headers: response.headers,
      body: responseBody,
    };
  } catch (error) {
    if (error.code === 'EPIPE') {
      return {
        status: '413 Payload Too Large (EPIPE)',
        headers: {},
        body: '',
      };
    }
    return { status: 'Error', headers: {}, body: String(error) };
  }
});

// Handle WebSocket connections
ipcMain.on('wss-connect', (event, { url, headers }) => {
  if (ws) {
    ws.close();
    ws = null;
  }

  ws = new WebSocket(url, { headers });
  ws.on('open', () => {
    event.sender.send('wss-event', { type: 'open' });
  });

  ws.on('message', (data) => {
    event.sender.send('wss-event', { type: 'message', data: data.toString() });
  });

  ws.on('error', (err) => {
    event.sender.send('wss-event', { type: 'error', error: String(err) });
  });

  ws.on('close', () => {
    event.sender.send('wss-event', { type: 'close' });
  });
});

ipcMain.on('wss-send', (_event, msg) => {
  if (ws) ws.send(msg);
});

// Handle ping requests
ipcMain.handle('ping-host', async (_event, host: string) => {
  return new Promise<number>((resolve, reject) => {
    const platform = process.platform;
    const cmd = platform === 'win32' ? `ping -n 1 ${host}` : `ping -c 1 ${host}`;
    const start = Date.now();

    exec(cmd, (error) => {
      if (error) return reject(error);

      const time = Date.now() - start;
      resolve(time);
    });
  });
});
